imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.2
  accelerometer_random_walk: 0.02
  gyroscope_noise_density: 0.05
  gyroscope_random_walk: 0.004
  model: calibrated
  rostopic: /imu/data
  time_offset: 0.0
  update_rate: 60.0
