#Accelerometers
accelerometer_noise_density: 0.2   #Noise density (continuous-time)
accelerometer_random_walk:   0.02   #Bias random walk

#Gyroscopes
gyroscope_noise_density:     0.05   #Noise density (continuous-time)
gyroscope_random_walk:       0.004   #Bias random walk

rostopic:                    /imu/data      #the IMU ROS topic
update_rate:                 60.0      #Hz (for discretization of the values above)
